version: '3'

services:

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --explicit_defaults_for_timestamp
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password 
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

  app:
    build:
      context: node
    container_name: app
    networks:
      - node-network
    volumes:
       - ./node:/usr/src/app
       - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
